// Code generated by goctl. DO NOT EDIT!
// Source: userRpc.proto

package server

import (
	"context"

	"userRpc/internal/logic"
	"userRpc/internal/svc"
	"userRpc/userRpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Ping(ctx context.Context, in *userRpc.Request) (*userRpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
