// Code generated by goctl. DO NOT EDIT!
// Source: userRpc.proto

//go:generate mockgen -destination ./userrpc_mock.go -package userrpcclient -source $GOFILE

package userrpcclient

import (
	"context"

	"userRpc/userRpc"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = userRpc.Request
	Response = userRpc.Response

	UserRpc interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := userRpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in)
}
