// Code generated by goctl. DO NOT EDIT!
// Source: userRpc.proto

//go:generate mockgen -destination ./user_rpc_mock.go -package userrpcclient -source $GOFILE

package userrpcclient

import (
	"context"

	"subModule/userRpc/userRpc"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Response     = userRpc.Response
	InfoRequest  = userRpc.InfoRequest
	InfoResponse = userRpc.InfoResponse
	Request      = userRpc.Request

	UserRpc interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
		Info(ctx context.Context, in *InfoRequest) (*InfoResponse, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := userRpc.NewUserRpcClient(m.cli.Conn())
	return client.Ping(ctx, in)
}

func (m *defaultUserRpc) Info(ctx context.Context, in *InfoRequest) (*InfoResponse, error) {
	client := userRpc.NewUserRpcClient(m.cli.Conn())
	return client.Info(ctx, in)
}
